import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='es'>
      <body className={`${inter.className} relative`}>
        <Navbar />
        {children}
        <footer className='absolute z-10 bottom-0 bg-headlines w-full'>
          Cami essen 2023
        </footer>
      </body>
    </html>
  );
}

/*

        
        

*/
